version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=SuperstrongPassword
    env_file:
      - db.env
    networks:
      - back

  redis:
    image: redis:alpine
    restart: always
    networks:
      - back

  app:
    build: ./app
    restart: always
    volumes:
      - ./cloud:/var/www/html
      - /home/ncdata/data:/var/www/html/data
      - /etc/localtime:/etc/localtime:ro
      - /home/youtube:/home/youtube
      - aria2-dl:/var/local/aria2c
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    ports:
      - 9024:80
      - 9028:443
    networks:
      - front
      - back

  cron:
    build: ./app
    restart: always
    volumes:
      - ./cloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - front
   
  collabora:
    image: collabora/code 
    container_name: collabora
    ports:
      - "127.0.0.1:9980:9980"
    cap_add:
      - MKNOD
    environment:
      - 'domain=cloud.domain.tld'
      - 'dictionaries=de,en'
    tty: true
    networks:
      - front

  elasticsearch:
    build: ./essearch
    restart: always
    #command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=esearch
      - xpack.security.enabled=false
      - node.name=esearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
      - network.host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./ncsearch-data/:/usr/share/elasticsearch/data
    networks:
      - back

volumes:
  db: 
  cloud:
  config: 
  aria2-dl:
  ncsearch-data:

networks:
  front:
    external:
      name: proxy-ssl
  back:
